# Generated by Django 5.2.12 on 2026-03-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(help_text='Emoji o nombre de icono', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud_centro', models.FloatField()),
                ('longitud_centro', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('piso', models.IntegerField(default=0)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.categoria')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='locations.escuela')),
            ],
        ),
    ]
